reviews:
  path_filters:
    - "!Tests/**/*.result"
    - "!Tests/**/*.source"
    - "!*.md"
    - "!**/XCTestManifests.swift"
    - "!**/LinuxMain.swift"
    - "!Tests/DiagnosticTests/**"
    - "!Makefile"
    - "!Package.swift"
    - "!*.sh"
    - "!Sources/Frontend/**"
    - "!Sources/Bocho/**"
    - "!Sources/Diagnostic/**"
    - "!Sources/swift-ast/**"
    - "!Sources/Tooling/**"
    - "!Tests/CommandLineTests/CLIOptionTests.swift"
    - "!Tests/DiagnosticTests/DiagnosticPoolTests.swift"
    - "!Tests/DotYanagibaTests/**"
    - "!Tests/ParserTests/Others/GenericOpeningChevronTests.swift"
    - "!Tests/ParserTests/Others/OptionalInPatternMatchingTests.swift"
    - "!Tests/ParserTests/Others/ParserErrorKindTests.swift"
    - "!Tests/ParserTests/Others/RangeOperatorTests.swift"
    - "!Tests/SemaTests/Sema+XCTest.swift"
    - "!Tests/SemaTests/SequenceExpressionFoldingTests.swift"
    - "!Tests/SourceTests/SourceFileTests.swift"
    - "!Tests/SourceTests/SourceLocationTests.swift"
    - "!Tests/SourceTests/SourceRangeTests.swift"
    - "!Tests/SwiftExtensionsTests/**"
    - "!Tests/LexerTests/LexerBooleanLiteralTests.swift"
    - "!Tests/LexerTests/LexerCheckpointTests.swift"
    - "!Tests/LexerTests/LexerCommentTests.swift"
    - "!Tests/LexerTests/LexerIdentifierTests.swift"
    - "!Tests/LexerTests/LexerNumericLiteralTests.swift"
    - "!Tests/LexerTests/LexerOperatorTests.swift"
    - "!Tests/LexerTests/RoleTests.swift"
    - "!Tests/LexerTests/ScannerTests.swift"
    - "!Tests/ParserTests/Attribute/ParserAttributeTests.swift"
    - "!Tests/ParserTests/Declaration/Modifier/ParserAccessLevelModifierTest.swift"
    - "!Tests/ParserTests/Declaration/Modifier/ParserMutationModifierTests.swift"
    - "!Tests/ParserTests/Declaration/ParserClassDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserCodeBlockTests.swift"
    - "!Tests/ParserTests/Declaration/ParserConstantDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserDeinitializerDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserEnumDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserExtensionDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserImportDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserOperatorDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserPrecedenceGroupDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserProtocolDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserSubscriptDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserTopLevelDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserTypealiasDeclarationTests.swift"
    - "!Tests/ParserTests/Declaration/ParserVariableDeclarationTests.swift"
    - "!Tests/ParserTests/Expression/Binary/ParserAssignmentOperatorExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Binary/ParserBinaryOperatorExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Binary/ParserSequenceExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Binary/ParserTernaryConditionalOperatorExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Binary/ParserTypeCastingOperatorExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Postfix/ParserForcedValueExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Postfix/ParserFunctionCallExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Postfix/ParserInitializerExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Postfix/ParserOptionalChainingExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Postfix/ParserPostfixOperatorExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Postfix/ParserPostfixSelfExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Postfix/ParserSubscriptExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Prefix/ParserInOutExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Prefix/ParserPrefixOperatorExpressionTests.swift"
    - "!Tests/ParserTests/Expression/Primary/ParserIdentifierExpressionTests.swift"
